# Generated by Django 2.2.4 on 2019-12-06 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logcompilation', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inlinecall',
            unique_together={('project', 'callsite', 'callee')},
        ),
    ]
